import Providers from "@/components/Providers";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Providers>
          <h1>Home Header</h1>
          <hr />
          {children}
          <hr />
          <h1>Home footer</h1>
        </Providers>
      </body>
    </html>
  );
}
